"use client";

import { useEffect, useState } from "react";

interface FontSpecimenProps {
  fontName: string;
  sourceType?: string;
  className?: string;
  style?: React.CSSProperties;
  children?: React.ReactNode;
}

function toGoogleFontsFamily(name: string) {
  return name.trim().replace(/\s+/g, "+");
}

/**
 * Map font names → the Google Fonts family to load for preview.
 *
 * Rules:
 * - Commercial / paid fonts: map to a visually similar Google Font
 * - Fontshare / free-download fonts: map to a Google Font of the same genre
 * - Open-source fonts NOT on Google Fonts (coding fonts, DaFont, etc.): map to closest match
 * - Fonts that ARE on Google Fonts under their own name need no entry here
 */
const GOOGLE_FONTS_PREVIEW_MAP: Record<string, string> = {
  // ── Serifs (commercial) ───────────────────────────────────────────────────
  "Garamond": "EB Garamond",
  "Garamond Premier Pro": "EB Garamond",
  "Adobe Garamond": "EB Garamond",
  "ITC Garamond": "EB Garamond",
  "Sabon": "EB Garamond",
  "Linotype Sabon": "EB Garamond",
  "Bembo": "EB Garamond",
  "Caslon Pro": "Libre Caslon Text",
  "Caslon 224": "Libre Caslon Text",
  "Didot": "Playfair Display",
  "Linotype Didot": "Playfair Display",
  "GFS Didot": "Playfair Display",
  "Bodoni": "Libre Bodoni",
  "Bodoni Moda": "Libre Bodoni",
  "Palatino": "Libre Baskerville",
  "Palatino Nova": "Libre Baskerville",
  "Palatino Linotype": "Libre Baskerville",
  "Book Antiqua": "Libre Baskerville",
  "Optima": "Noto Serif Display",
  "Optima Nova": "Noto Serif Display",
  "Hoefler Text": "Libre Baskerville",
  "Minion Pro": "Source Serif 4",
  "Warnock Pro": "Source Serif 4",
  "Kepler Std": "Source Serif 4",
  "Arno Pro": "Source Serif 4",
  "Utopia Std": "Source Serif 4",
  "Chaparral Pro": "Bitter",
  "Chronicle Display": "Playfair Display",
  "Chronicle Text": "Source Serif 4",
  "Mercury Text": "Source Serif 4",
  "Sentinel": "Bitter",
  "Clarendon": "Zilla Slab",
  "Century Gothic": "Poppins",
  "Calluna": "Crimson Pro",
  "Freight Text": "Crimson Pro",
  "Freight Text Pro": "Crimson Pro",
  "Freight Display": "Playfair Display",
  "Freight Display Pro": "Playfair Display",
  "Freight Big Pro": "Playfair Display",
  "Freight Neo Pro": "DM Sans",
  "Freight Sans": "Source Sans 3",
  "Freight Sans Pro": "Source Sans 3",
  "Freight Micro Pro": "Source Serif 4",
  "Cambon": "DM Serif Display",
  "Signifier": "DM Serif Display",
  "Financier Display": "Playfair Display",
  "Tiempos Headline": "Playfair Display",
  "Tiempos Text": "Source Serif 4",
  "Tiempos Fine": "Playfair Display",
  "Canela": "DM Serif Display",
  "Canela Text": "Crimson Pro",
  "Canela Condensed": "DM Serif Display",
  "Canela Deck": "DM Serif Display",
  "Canela Deckular": "DM Serif Display",
  "Domaine": "DM Serif Display",
  "Domaine Display": "DM Serif Display",
  "Domaine Display Narrow": "DM Serif Display",
  "Domaine Text": "Source Serif 4",
  "Domaine Sans": "DM Sans",
  "GT Sectra": "Crimson Pro",
  "Harriet": "Crimson Pro",
  "Harriet Display": "Playfair Display",
  "Reckless Neue": "Crimson Pro",
  "Larish Neue": "Playfair Display",
  "Feijoa": "Bitter",
  "Trajan Pro": "Cinzel",
  "Moret": "DM Serif Display",
  "Blanco": "Newsreader",
  "Heldane": "DM Serif Display",
  "Heldane Text": "Source Serif 4",
  "Darby Serif Display": "Playfair Display",
  "Darby Serif": "Source Serif 4",
  "Caponi Display": "Playfair Display",
  "New Spirit": "Playfair Display",
  "Roslindale": "Lora",
  "Gimlet Display": "Playfair Display",
  "Gimlet Text": "Source Serif 4",
  "Lyon Text": "Source Serif 4",
  "Lyon Display": "Playfair Display",
  "Publico Text": "Source Serif 4",
  "Publico Headline": "Playfair Display",
  "Epicene Display": "Playfair Display",
  "Epicene Display Italic": "Playfair Display",
  "Epicene Text": "Crimson Pro",
  "Austin": "Playfair Display",
  "Portrait Text": "Source Serif 4",
  "Stag": "Zilla Slab",
  "Pensum Pro": "Source Serif 4",
  "Skolar PE": "Crimson Pro",
  "Skolar Sans Latin": "Source Sans 3",
  "Coranto 2": "Source Serif 4",
  "Eskal": "Zilla Slab",
  "Bely Display": "Playfair Display",
  "Operetta 12": "Playfair Display",
  "Triptych": "Playfair Display",
  "Souvenir": "Lora",
  "Atlas Typewriter": "Courier Prime",
  "Leitura News": "Source Serif 4",
  "Migra": "Playfair Display",
  "Migra Italic": "Playfair Display",
  "Poltawski Nowy": "Lora",
  "Piazzolla": "Lora",
  "Imbue": "Source Serif 4",
  "Newsreader": "Newsreader",
  "Reforma 1918": "Source Serif 4",
  "Reforma 2018": "Source Sans 3",
  "Produkt": "Source Serif 4",

  // ── Sans-serifs (commercial) ──────────────────────────────────────────────
  "Helvetica": "Inter",
  "Helvetica Neue": "Inter",
  "Helvetica Now": "Inter",
  "Helvetica Now Display": "Inter",
  "Helvetica Now Micro": "Inter",
  "Neue Haas Grotesk": "Inter",
  "Neue Haas Grotesk Display": "Inter",
  "Neue Haas Grotesk Text": "Inter",
  "Neue Haas Unica": "Inter",
  "Neue Haas Unica Pro": "Inter",
  "Frutiger": "Source Sans 3",
  "Neue Frutiger": "Source Sans 3",
  "Myriad Pro": "Source Sans 3",
  "Cronos Pro": "Source Sans 3",
  "Acumin Pro": "Source Sans 3",
  "Acumin Variable Concept": "Source Sans 3",
  "Avenir": "Nunito Sans",
  "Avenir Next": "Nunito Sans",
  "Futura": "Nunito",
  "Futura PT": "Nunito",
  "Neue Plak": "Nunito",
  "Gotham": "Montserrat",
  "Proxima Nova": "Montserrat",
  "Proxima Nova Condensed": "Montserrat",
  "Proxima Soft": "Nunito",
  "Gill Sans": "Lato",
  "Gill Sans Nova": "Lato",
  "Aktiv Grotesk": "Inter",
  "Aktiv Grotesk Condensed": "Inter",
  "Aktiv Grotesk Extended": "Inter",
  "Effra": "Inter",
  "Graphik": "Inter",
  "Graphik Condensed": "Inter",
  "Graphik Wide": "Inter",
  "Neue Montreal": "Inter",
  "Monument Extended": "Oswald",
  "Suisse Int'l": "Inter",
  "Suisse Int'l Mono": "JetBrains Mono",
  "Suisse Works": "Source Serif 4",
  "Founders Grotesk": "Work Sans",
  "Founders Grotesk Condensed": "Work Sans",
  "Founders Grotesk Mono": "JetBrains Mono",
  "National 2": "Inter",
  "Calibre": "Work Sans",
  "Sohne": "Inter",
  "Sohne Breit": "Inter",
  "Sohne Mono": "JetBrains Mono",
  "Sohne Schmal": "Oswald",
  "Maison Neue": "DM Sans",
  "Maison Neue Mono": "JetBrains Mono",
  "Sofia Pro": "DM Sans",
  "Basier Circle": "DM Sans",
  "Basier Circle Mono": "JetBrains Mono",
  "Basier Square": "DM Sans",
  "Basier Square Mono": "JetBrains Mono",
  "Centra No.2": "DM Sans",
  "Centra No 2": "DM Sans",
  "Geomanist": "Poppins",
  "Eurostile": "Rajdhani",
  "Druk": "Anton",
  "Druk Wide": "Anton",
  "Druk Text": "Anton",
  "Action Condensed": "Anton",
  "Verlag": "Nunito Sans",
  "ITC Avant Garde": "Poppins",
  "ITC Avant Garde Gothic Pro": "Poppins",
  "ITC Franklin Gothic": "Libre Franklin",
  "Brown": "DM Sans",
  "Aeonik": "DM Sans",
  "Aeonik Mono": "JetBrains Mono",
  "Aeonik Pro": "DM Sans",
  "Lineto Circular": "DM Sans",
  "ABC Diatype": "DM Sans",
  "ABC Diatype Mono": "JetBrains Mono",
  "ABC Monument Grotesk": "Inter",
  "ABC Whyte": "Inter",
  "ABC Favorit": "Inter",
  "ABC Arizona": "Source Serif 4",
  "PP Mori": "DM Sans",
  "PP Neue Machina": "Space Grotesk",
  "PP Right Grotesk": "Work Sans",
  "Neue Machina": "Space Grotesk",
  "GT Alpina": "DM Serif Display",
  "GT Alpina Condensed": "DM Serif Display",
  "GT America": "Work Sans",
  "GT America Condensed": "Oswald",
  "GT America Extended": "Work Sans",
  "GT America Mono": "JetBrains Mono",
  "GT Walsheim": "Nunito",
  "GT Walsheim Condensed": "Nunito",
  "GT Zirkon": "Nunito",
  "GT Maru": "Nunito",
  "GT Flexa": "DM Sans",
  "GT Ultra": "Inter",
  "Sharp Grotesk": "Inter",
  "Sharp Sans": "Inter",
  "Sharp Sans No2": "Inter",
  "Sharp Grotesk Display": "Inter",
  "Apercu": "DM Sans",
  "Apercu Condensed": "DM Sans",
  "Apercu Mono": "JetBrains Mono",
  "Raisonné": "DM Sans",
  "TT Commons": "DM Sans",
  "TT Commons Pro": "DM Sans",
  "TT Norms Pro": "DM Sans",
  "TT Hoves": "DM Sans",
  "TT Fors": "DM Sans",
  "TT Travels": "Nunito",
  "TT Interphases": "DM Sans",
  "TT Ramillas": "Playfair Display",
  "TT Serafim": "Zilla Slab",
  "Euclid Circular A": "DM Sans",
  "Euclid Circular B": "DM Sans",
  "Euclid Flex": "DM Sans",
  "Euclid Square": "DM Sans",
  "Euclid Triangle": "DM Sans",
  "Editorial New": "Newsreader",
  "Obviously": "Anybody",
  "Obviously Wide": "Anybody",
  "Obviously Condensed": "Anybody",
  "Styrene A": "Inter",
  "Styrene B": "Inter",
  "Idlewild": "Work Sans",
  "Pitch": "Space Mono",
  "Agipo": "Space Grotesk",
  "Whitney": "Source Sans 3",
  "Tungsten": "Oswald",
  "Knockout": "Oswald",
  "Ringside": "Oswald",
  "Archer": "Bitter",
  "Decimal": "Roboto Mono",
  "Neue DIN": "Inter",
  "Korolev": "Oswald",
  "Veneer": "Anton",
  "Glosa Text": "Crimson Pro",
  "Tablet Gothic": "Zilla Slab",
  "Gimbal Grotesque": "Inter",
  "Adelle Sans": "Source Sans 3",
  "Adelle": "Zilla Slab",
  "Benton Sans": "Source Sans 3",
  "Benton Sans Condensed": "Oswald",
  "Bureau Grotesque": "Work Sans",
  "Stag Sans": "Source Sans 3",
  "Fakt Pro": "Source Sans 3",
  "Fakt Soft": "Nunito",
  "Moderat": "DM Sans",
  "Object Sans": "DM Sans",
  "Articulat CF": "Work Sans",
  "Gellix": "DM Sans",
  "Geist Sans": "Inter",
  "Geist Mono": "JetBrains Mono",
  "Mona Sans": "Inter",
  "Hubot Sans": "Inter",
  "Uncut Sans": "Inter",
  "Basement Grotesque": "Anton",
  "Formula Condensed": "Oswald",
  "Neue Regrade": "Inter",
  "Neue World": "Inter",
  "Bebas Neue Pro": "Bebas Neue",
  "Px Grotesk": "DM Sans",
  "Px Grotesk Light": "DM Sans",
  "Scto Grotesk A": "Inter",
  "Whyte Inktrap": "Inter",
  "Forma DJR Micro": "Source Sans 3",
  "Forma DJR Banner": "Source Sans 3",
  "Ingra": "Inter",
  "Colfax": "DM Sans",
  "Quasimoda": "Source Sans 3",
  "Halyard Display": "DM Sans",
  "Halyard Micro": "DM Sans",
  "Fedra Sans": "Source Sans 3",
  "Greta Sans": "Source Sans 3",
  "Brioni Text": "Source Serif 4",
  "Sunday": "Nunito",
  "Doyle": "Playfair Display",

  // ── Monospace (commercial) ────────────────────────────────────────────────
  "Operator Mono": "JetBrains Mono",
  "Berkeley Mono": "JetBrains Mono",
  "MonoLisa": "JetBrains Mono",
  "Dank Mono": "Fira Code",
  "Gintronic": "Fira Code",
  "Input Mono": "JetBrains Mono",
  "Input Sans": "Source Sans 3",
  "Input Serif": "Source Serif 4",

  // ── Fontshare / free-download (not directly on Google Fonts) ─────────────
  "Satoshi": "DM Sans",
  "Switzer": "Work Sans",
  "General Sans": "DM Sans",
  "Cabinet Grotesk": "DM Sans",
  "Chillax": "Nunito",
  "Supreme": "DM Sans",
  "Author": "DM Sans",
  "Tanker": "Space Grotesk",
  "Tanker Bold": "Space Grotesk",
  "Nippo": "Space Grotesk",
  "Nippo Variable": "Space Grotesk",
  "Alpino": "Nunito",
  "Excon": "Space Grotesk",
  "Synonyme": "Oswald",
  "Array": "JetBrains Mono",
  "Boska": "Playfair Display",
  "Zodiak": "DM Serif Display",
  "Zodiak Display": "DM Serif Display",
  "Erode": "Crimson Pro",
  "Melodrama": "Playfair Display",
  "Recia": "Merriweather",
  "Aspekta": "DM Sans",
  "Technor": "Space Grotesk",
  "Kola": "DM Serif Display",
  "Sentient": "Crimson Pro",
  "Sentient Italic": "Crimson Pro",
  "Bespoke Serif": "Playfair Display",
  "Bespoke Slab": "Zilla Slab",
  "Bespoke Stencil": "Oswald",
  "Gambarino": "Playfair Display",
  "Ranade": "DM Sans",
  "Deca": "DM Sans",
  "Formularone": "Oswald",
  "Clashdisplay": "Space Grotesk",
  "Clash Display": "Space Grotesk",
  "Clash Grotesk": "Space Grotesk",
  "Khand": "DM Sans",
  "Telma": "Playfair Display",
  "Gyst": "DM Sans",
  "Aller": "Source Sans 3",
  "Antonia H1": "Source Sans 3",
  "Atkinson Hyperlegible Next": "DM Sans",

  // ── Open-source fonts NOT on Google Fonts ─────────────────────────────────
  // Coding / monospace
  "0xProto": "JetBrains Mono",
  "Agave": "JetBrains Mono",
  "Departure Mono": "Space Mono",
  "Iosevka": "JetBrains Mono",
  "Lilex": "JetBrains Mono",
  "JetBrains Mono NL": "JetBrains Mono",
  "Commit Mono": "JetBrains Mono",
  "Victor Mono": "Fira Code",
  "Hack": "Fira Code",
  "Cascadia Mono": "JetBrains Mono",
  "Cascadia Code": "JetBrains Mono",
  "Maple Mono": "JetBrains Mono",
  "Nerd Fonts (generic)": "JetBrains Mono",
  "Monaspace Neon": "JetBrains Mono",
  "Monaspace Argon": "JetBrains Mono",
  "Monaspace Xenon": "Zilla Slab",
  "Monaspace Radon": "Caveat",
  "Monaspace Krypton": "JetBrains Mono",
  "Intel One Mono": "JetBrains Mono",
  "Martian Mono": "JetBrains Mono",

  // Display / decorative (DaFont, etc.)
  "28 Days Later": "Creepster",
  "Chomsky": "UnifrakturMaguntia",
  "Azonix": "Orbitron",
  "Edo": "Permanent Marker",
  "Champagne & Limousines": "Raleway",
  "Lemon Milk": "Nunito",
  "Coolvetica": "Raleway",
  "College": "Oswald",
  "Freshman": "Oswald",
  "Road Rage": "Permanent Marker",
  "Old London": "UnifrakturMaguntia",
  "Unifraktur Maguntia": "UnifrakturMaguntia",
  "Harabara": "Oswald",
  "Steelfish": "Oswald",
  "Nasalization": "Orbitron",
  "Liquid Crystal": "Orbitron",
  "Furore": "Orbitron",
  "Matriks": "Oswald",
  "Quikhand": "Permanent Marker",
  "Blackout Midnight": "Anton",
  "Capture It": "Oswald",
  "Bourton": "Josefin Sans",
  "28-days-later": "Creepster",

  // Augment / OH no Type
  "Augment": "Space Grotesk",
  "Ohno Blazeface": "Space Grotesk",
  "Ohno Softie": "Nunito",
  "Degular": "DM Sans",
  "Covik Sans": "DM Sans",
  "Meche": "DM Sans",

  // System / proprietary
  "SF Pro": "Inter",
  "SF Pro Display": "Inter",
  "SF Pro Text": "Inter",
  "Segoe UI": "Inter",
  "Arial": "Inter",
  "Calibri": "Inter",
  "Cambria": "Source Serif 4",
  "Comic Sans MS": "Pangolin",
  "Courier New": "Courier Prime",
  "Georgia": "Source Serif 4",
  "Impact": "Anton",
  "Lucida Console": "JetBrains Mono",
  "Lucida Grande": "DM Sans",
  "Tahoma": "DM Sans",
  "Times New Roman": "Source Serif 4",
  "Trebuchet MS": "Work Sans",
  "Verdana": "Source Sans 3",
  "Wingdings": "Noto Sans Symbols",

  // ── Open-source fonts on Google Fonts (map to themselves) ────────────────
  "Acme": "Acme",
  "Alfa Slab One": "Alfa Slab One",
  "Allura": "Allura",
  "Amiri": "Amiri",
  "Anton": "Anton",
  "Architects Daughter": "Architects Daughter",
  "Archivo": "Archivo",
  "Archivo Black": "Archivo Black",
  "Archivo Narrow": "Archivo Narrow",
  "Atkinson Hyperlegible": "Atkinson Hyperlegible",
  "Audiowide": "Audiowide",
  "Baloo 2": "Baloo 2",
  "Balsamiq Sans": "Balsamiq Sans",
  "Bangers": "Bangers",
  "Barlow": "Barlow",
  "Bellefair": "Bellefair",
  "BenchNine": "BenchNine",
  "Black Ops One": "Black Ops One",
  "Bree Serif": "Bree Serif",
  "Brygada 1918": "Brygada 1918",
  "Bubblegum Sans": "Bubblegum Sans",
  "Bungee": "Bungee",
  "Cabin": "Cabin",
  "Cantarell": "Cantarell",
  "Cantata One": "Cantata One",
  "Catamaran": "Catamaran",
  "Chewy": "Chewy",
  "Chivo Mono": "Chivo Mono",
  "Coda": "Coda",
  "Comfortaa": "Comfortaa",
  "Coming Soon": "Coming Soon",
  "Crete Round": "Crete Round",
  "Cuprum": "Cuprum",
  "Darker Grotesque": "Darker Grotesque",
  "Days One": "Days One",
  "Didact Gothic": "Didact Gothic",
  "DM Mono": "DM Mono",
  "DM Sans": "DM Sans",
  "Dosis": "Dosis",
  "Encode Sans Condensed": "Encode Sans Condensed",
  "Faustina": "Faustina",
  "Figtree": "Figtree",
  "Fira Mono": "Fira Mono",
  "Fira Sans": "Fira Sans",
  "Fira Sans Condensed": "Fira Sans Condensed",
  "Fjalla One": "Fjalla One",
  "Forum": "Forum",
  "Francois One": "Francois One",
  "Fredoka One": "Fredoka One",
  "Fugaz One": "Fugaz One",
  "Gantari": "Gantari",
  "Gloria Hallelujah": "Gloria Hallelujah",
  "Graduate": "Graduate",
  "Grandstander": "Grandstander",
  "Gravitas One": "Gravitas One",
  "Heebo": "Heebo",
  "Hepta Slab": "Hepta Slab",
  "IBM Plex Sans": "IBM Plex Sans",
  "Indie Flower": "Indie Flower",
  "Inknut Antiqua": "Inknut Antiqua",
  "Instrument Sans": "Instrument Sans",
  "Inter": "Inter",
  "Josefin Slab": "Josefin Slab",
  "Jost": "Jost",
  "K2D": "K2D",
  "Karla": "Karla",
  "Kaushan Script": "Kaushan Script",
  "Klee One": "Klee One",
  "Kreon": "Kreon",
  "Lalezar": "Lalezar",
  "League Spartan": "League Spartan",
  "Lexend Exa": "Lexend Exa",
  "Lobster": "Lobster",
  "Lobster Two": "Lobster Two",
  "Lora": "Lora",
  "Macondo": "Macondo",
  "Maitree": "Maitree",
  "Manrope": "Manrope",
  "Marck Script": "Marck Script",
  "Markazi Text": "Markazi Text",
  "Maven Pro": "Maven Pro",
  "Merriweather": "Merriweather",
  "Merriweather Sans": "Merriweather Sans",
  "Michroma": "Michroma",
  "Miriam Libre": "Miriam Libre",
  "Moirai One": "Moirai One",
  "Monoton": "Monoton",
  "Montagu Slab": "Montagu Slab",
  "Montserrat": "Montserrat",
  "Mooli": "Mooli",
  "Mukta": "Mukta",
  "Mulish": "Mulish",
  "Noto Sans": "Noto Sans",
  "Noto Sans Arabic": "Noto Sans Arabic",
  "Nova Mono": "Nova Mono",
  "Nunito": "Nunito",
  "Open Sans": "Open Sans",
  "Orbitron": "Orbitron",
  "Outfit": "Outfit",
  "Oxanium": "Oxanium",
  "Palanquin": "Palanquin",
  "Pangolin": "Pangolin",
  "Patrick Hand": "Patrick Hand",
  "Philosopher": "Philosopher",
  "Phudu": "Phudu",
  "Pinyon Script": "Pinyon Script",
  "Pirata One": "Pirata One",
  "Playfair Display": "Playfair Display",
  "Plus Jakarta Sans": "Plus Jakarta Sans",
  "Poiret One": "Poiret One",
  "Press Start 2P": "Press Start 2P",
  "Prompt": "Prompt",
  "PT Sans": "PT Sans",
  "Public Sans": "Public Sans",
  "Questrial": "Questrial",
  "Quicksand": "Quicksand",
  "Rajdhani": "Rajdhani",
  "Raleway": "Raleway",
  "Rampart One": "Rampart One",
  "Reggae One": "Reggae One",
  "Rethink Sans": "Rethink Sans",
  "Righteous": "Righteous",
  "Roboto": "Roboto",
  "Rock Salt": "Rock Salt",
  "Rokkitt": "Rokkitt",
  "Rubik": "Rubik",
  "Ruda": "Ruda",
  "Russo One": "Russo One",
  "Saira": "Saira",
  "Seaweed Script": "Seaweed Script",
  "Secular One": "Secular One",
  "Sen": "Sen",
  "Shadows Into Light": "Shadows Into Light",
  "Shantell Sans": "Shantell Sans",
  "Signika": "Signika",
  "Source Sans Pro": "Source Sans 3",
  "Source Serif Pro": "Source Serif 4",
  "Space Grotesk": "Space Grotesk",
  "Special Elite": "Special Elite",
  "Spectral": "Spectral",
  "Stardos Stencil": "Stardos Stencil",
  "STIX Two Text": "STIX Two Text",
  "Suez One": "Suez One",

  // Open-source fonts NOT on Google Fonts → closest substitute
  "Apfel Grotezk": "DM Sans",
  "DejaVu Sans": "Open Sans",
  "DejaVu Sans Mono": "JetBrains Mono",
  "DejaVu Serif": "Source Serif 4",
  "Liberation Mono": "JetBrains Mono",
  "Liberation Sans": "Inter",
  "Liberation Serif": "Source Serif 4",
  "Scriptina": "Dancing Script",
  "Redaction": "Source Serif 4",
  "Reforma": "Source Serif 4",
  "Estedad": "DM Sans",

  // ── Free-download fonts (not on Google Fonts) ─────────────────────────────
  "Bebas": "Bebas Neue",
  "Blogger Sans": "Nunito",
  "Chunk Five": "Playfair Display",
  "Exo Font": "Exo 2",
  "Gambetta": "Crimson Pro",
  "Geist": "Geist Sans",
  "Integral CF": "Space Grotesk",
  "Kelsi": "DM Sans",
  "Khand Fontshare": "Khand",
  "League Gothic": "Oswald",
  "MADE Outer Sans": "Inter",
  "Nexa": "Nunito",
  "Nexa Rust": "Zilla Slab",
  "Overused Grotesk": "DM Sans",
  "Panchang": "Playfair Display",
  "Panton": "Nunito",
  "Phenomena": "Nunito",
  "Quincy CF": "Bitter",
  "Sometype Mono": "JetBrains Mono",
  "Stardom": "Playfair Display",
  "Street Ruler": "Oswald",

  // ── Commercial fonts (additional — beyond original list) ──────────────────
  "Akzidenz Grotesk": "Work Sans",
  "Agrandir": "Plus Jakarta Sans",
  "Area": "DM Sans",
  "Atlas Grotesk": "DM Sans",
  "Basis Grotesque Pro": "Inter",
  "Baskerville": "Libre Baskerville",
  "Baskerville URW": "Libre Baskerville",
  "Beausite Classic": "DM Sans",
  "Beausite Grand": "DM Sans",
  "Bluu Next": "Playfair Display",
  "Brandon Grotesque": "Nunito Sans",
  "Burgess": "Source Serif 4",
  "Caponi": "Playfair Display",
  "Capsize": "DM Sans",
  "Caslon": "Libre Caslon Text",
  "Chiswick": "Playfair Display",
  "Circular": "DM Sans",
  "Decima Mono Pro": "JetBrains Mono",
  "Dharma Gothic": "Oswald",
  "Elena": "Crimson Pro",
  "Fakt": "DM Sans",
  "Fenwick": "Newsreader",
  "FF DIN": "Inter",
  "FF DIN Round": "Nunito",
  "FF Mark": "Inter",
  "FF Meta": "Source Sans 3",
  "FF Meta Serif": "Source Serif 4",
  "FF Scala": "Source Serif 4",
  "FF Tisa": "Source Serif 4",
  "Filosofia": "Playfair Display",
  "Flama": "Oswald",
  "Flecha M": "DM Serif Display",
  "Forma DJR": "Source Sans 3",
  "Franklin Gothic": "Libre Franklin",
  "Futura PT Condensed": "Oswald",
  "Galaxie Copernicus": "Spectral",
  "Geograph": "DM Sans",
  "Ginto": "Inter",
  "Graebenbach": "Work Sans",
  "Grenette": "DM Serif Display",
  "GT Pressura": "Space Grotesk",
  "Halyard": "DM Sans",
  "Hightower Text": "Crimson Pro",
  "Hobeaux Rococeaux": "Josefin Sans",
  "ITC Galliard Pro": "Crimson Pro",
  "ITC Lubalin Graph": "Josefin Slab",
  "Ivar": "Playfair Display",
  "Kazimir": "Crimson Pro",
  "Konnect": "DM Sans",
  "Landmark": "Playfair Display",
  "Lyon": "Playfair Display",
  "Mallory": "Work Sans",
  "Manuka": "DM Serif Display",
  "Matrix II": "Playfair Display",
  "Messina Sans": "DM Sans",
  "Morion": "DM Serif Display",
  "Mrs Eaves": "EB Garamond",
  "Museo Sans": "Nunito",
  "Neo Sans": "Inter",
  "Neutraface": "Questrial",
  "Neutraface 2": "Questrial",
  "Noe Display": "Playfair Display",
  "Noe Text": "Source Serif 4",
  "Nocturno": "Source Serif 4",
  "Ogg": "Playfair Display",
  "Pangram Sans": "DM Sans",
  "Platform": "Inter",
  "Plantin": "Source Serif 4",
  "Portrait": "Source Serif 4",
  "Recoleta": "Lora",
  "Riforma": "Work Sans",
  "Roc Grotesk": "Inter",
  "Saans": "DM Sans",
  "Sang Bleu Kingdom": "Playfair Display",
  "Saol": "DM Serif Display",
  "Scala Pro": "Source Serif 4",
  "Seravek": "Nunito",
  "Sirba": "Source Serif 4",
  "Skolar": "Source Serif 4",
  "Skolar Sans": "Source Sans 3",
  "Söhne": "Inter",
  "Soleil": "Source Sans 3",
  "Stabil Grotesk": "Inter",
  "Stratos": "Inter",

  // ── Newly added fonts ─────────────────────────────────────────────────────
  "Google Sans": "Google Sans",
  "Google Sans Flex": "Google Sans Flex",
  "TT Firs": "DM Sans",
  "Exposure": "Playfair Display",
  "Nassim": "Noto Nastaliq Urdu",
  "Amandine": "Playfair Display",
};

export default function FontSpecimen({
  fontName,
  sourceType,
  className,
  style,
  children,
}: FontSpecimenProps) {
  const [loaded, setLoaded] = useState(false);

  // Map entry takes priority — it means we have a known substitute
  const mapEntry = GOOGLE_FONTS_PREVIEW_MAP[fontName];

  // Only try loading by font name directly when it's actually on Google Fonts
  const isOnGoogleFonts = !sourceType || sourceType === "google-fonts";

  // Resolution order:
  // 1. Explicit map entry (substitute for any font type)
  // 2. Direct load by name if it's a Google Font
  // 3. null → render with site fallback font
  const fontToLoad = mapEntry ?? (isOnGoogleFonts ? fontName : null);

  useEffect(() => {
    if (!fontToLoad) {
      setLoaded(true);
      return;
    }

    const family = toGoogleFontsFamily(fontToLoad);
    const linkId = `gf-${family}`;

    if (document.getElementById(linkId)) {
      setLoaded(true);
      return;
    }

    const link = document.createElement("link");
    link.id = linkId;
    link.rel = "stylesheet";
    link.href = `https://fonts.googleapis.com/css2?family=${family}:ital,wght@0,400;0,700;1,400&display=swap`;
    link.onload = () => setLoaded(true);
    link.onerror = () => setLoaded(true);
    document.head.appendChild(link);
  }, [fontToLoad]);

  const displayFont = fontToLoad || fontName;
  const fontFamily = `"${displayFont}", var(--font-display), Georgia, serif`;

  return (
    <span
      className={className}
      style={{
        fontFamily,
        transition: "opacity 300ms ease",
        opacity: loaded ? 1 : 0.6,
        ...style,
      }}
    >
      {children ?? fontName}
    </span>
  );
}
